Add CHANGELOG and Update README
turbot/flowpipe-mod-github pull request #9
Opened 2023-12-15 08:10 UTC by vkumbha

### Checklist
- [ ] Issue(s) linked

2023-12-19 14:05 UTC, cbruno10 requested changes
@vkumbha Please see suggestion, thanks!

2023-12-19 14:05 UTC, cbruno10 commented on CHANGELOG.md
> +- Added 35+ pipelines to enable seamless integration of GitHub services and more. For usage information and a full list of pipelines, please see [GitHub Mod for Flowpipe](https://hub.flowpipe.io/mods
```suggestion
- Added 35+ pipelines to make it easy to connect your issue, pull request, repository resources and more. For usage information and a full list of pipelines, please see [GitHub Mod for Flowpipe](https://hub.flowpipe.io/mods/turbot/github).
```

2024-01-11 13:22 UTC, bigdatasourav approved these changes

2024-01-11 17:14 UTC, cbruno10 approved these changes

2024-02-07 12:04 UTC, merged